name: Jonathan Piedra - 
markdown: redcarpet
pygments: true

permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #
    
ga_id: #
ga_username: #
        
timezone: #

gallery:
    dir: assets/images/gmis
    url: /assets/images/gmis
    thumb_width: 150
    thumb_height: 150
    columns: 3       