name: Jonathan Piedra - 
markdown: redcarpet
pygments: true
encoding: UTF-8

permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #
    
ga_id: #
ga_username: #
        
timezone: #
