name: Jonathan Piedra - 
markdown: redcarpet
encoding: UTF-8
static_tags:
    - python
    - maze
    - javascript
    - webdev
    - squarespace

static_tags-foruselater:
    - unrealscript
    - c
    - pygame
    - sockets
    - assembler

permalink: /:year/:month/:title/
owner:
    name: Jonathan Piedra
    github: jpiedra
        
ga_id: #
ga_username: #
        
timezone: #
